#!/bin/sh
# prerm script for specter-framework
#
# see: dh_installdeb(1)

#set -e #we want to ignore gacutil errors if user manually removed the libs

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

if [ -x /usr/bin/cli-gacutil ]; then
    GACUTIL="/usr/bin/cli-gacutil"
else
    GACUTIL="/usr/bin/gacutil"
fi


case "$1" in
    remove|deconfigure)
    env $GACUTIL -u Specter.Framework
    env $GACUTIL -u Specter.Util
    ;;

    upgrade)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
